# display_name and display_name_plural are old deprecated; Rails i18n is now
# used for display names. See service_type_values.rb.
#
# Which makes this file at present just a list of names and ids; if we had
# to do it over, we'd do this differently. 
#
# You can add your own additional service types in a local app config/service_type_values.yml, 
# or by calling (TODO)
fulltext:
  display_name: Electronic Version
  display_name_plural: Electronic Versions
  
holding:
  display_name: Copy in Library
  display_name_plural: Copies in Library
  
document_delivery:
  display_name: Request Service
  display_name_plural: Request Services
  
help:
  display_name: Help Link
  display_name_plural: Help Links

# Not currently used
web_link:
  display_name: Web Result
  display_name_plural: Web Results

# Not currently used. 
relevant_link:
  display_name: Closest Web Result
  
abstract:
  display_name: Abstract
  display_name_plural: Abstracts
  
table_of_contents:
  display_name: Table of Contents
  display_name_plural: Tables of Contents

cover_image:
  display_name: Cover Image
  display_name_plural: Cover Images

# "See also" links to known destinations, like Amazon or OCLC
highlighted_link:
  display_name: See Also Link
  display_name_plural: See Also Links
  
# Link to search holdings, generally with a count given, ie "5 possible matches". 
holding_search:
  display_name: Copy in Library
  display_name_plural: Copies in Library
  
# This is meant for 'fulltext' from such sources as the OPAC/ILS, where
# it will always be a title-level link, and dates of coverage usually
# aren't checked. DEPRECATED. No longer used, use a fulltext wtih :coverage_checked
# and/or :can_link_to_article set to false. 
fulltext_title_level:
  display_name: Electronic Text Version
  
audio:
  display_name: Digital Audio

# A search inside tool, presented with a search box for user. 
search_inside:
  display_name: Search Inside Tool

# A tool that will enhance the Referent metadata. Not always advertised
# properly yet. 
referent_enhance:
  display_name: More Information

# Link to partial text, as in Amazon or Google Books that don't have
# full text, only excerpts. 
excerpts:
  display_name: Limited Excerpts
  
cited_by:
  display_name: Article that cites this
  display_name_plural: Articles that cite this

# Used by ISI and Scopus at present. Maybe more later. 
# "More like this" links. 
similar:
  display_name: "Similar Articles"
  
  
# Not sure what this is used for. Think it's a typo for abstract. 
description:
  display_name: Description
  
# Not sure if this is used for anything yet, but some services generate
subject:
  display_name: Subject
  
# Not used yet by views
similar_item:
  display_name: Similar Item

# Used to save/send the citation/holdings
export_citation:
  display_name: Export tool
  display_name_plural: Export Tools

primo_source:
  display_name: Primo Source

